<?php
/**
 * @file   : MailPHPUnitTest.php
 * @time   : 11:46
 * @date   : 2021/10/5
 * @mail   : 9727005@qq.com
 * @creator: ShanDong Xiedali
 * @company: HiLand & RainyTop
 */

namespace PHP\Study\SymfonyStudy\OptionsResolver;

use PHPUnit\Framework\TestCase;

class MailPHPUnitTest extends TestCase
{
    private ?Mail $mail = null;

    /**
     * 一定要跟基类里面的setUp方法签名一致(包括void返回值)
     */
    protected function setUp(): void
    {
        self::init();
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    private function init()
    {
        if ($this->mail == null) {
            $this->mail = new Mail(["host" => "smtp.gmail.com", "port" => "995"]);
        }
    }

    public function testGetHost()
    {
        $actual = $this->mail->getHost();
        $expected = "smtp.gmail.com";
        self::assertEquals($expected, $actual);
    }

    public function testGetOptionItem()
    {
        /**
         * 读取用OptionResolver设置的默认值
         */
        $actual = $this->mail->getOptionItem("userName");
        $expected = "myName";
        self::assertEquals($expected, $actual);
    }
}
